### ISSUE TITLE
Allow adding custom level mappings

### ISSUE THREAD

**Issue by hifi** [samber/slog-zerolog#2]
I'm integrating with a library that uses slog and I've also added a custom trace level to it for spammy trace logs as slog doesn't have such level by default.

Currently those trace logs will come out on the debug level of zerolog but it'd be very useful to be able to add custom mappings through the log options. Because slog allows defining custom log levels I can imagine having full remapping freedom is necessary, maybe through a callback function to be able to use integer comparison?

Alternatively a quick fix would be to map any level that is higher than debug on slog to trace on zerolog.

**Comment by samber** [comment]
I just exposed the LogLevels map externaly.

-> v2.1.0

**Comment by hifi** [comment]
That works, thanks!
